kind: Service
apiVersion: v1
metadata:
  name:  hello-world-nginx-svc_lb
spec:
  selector:
    app:  hello-world-nginx
  type:  LoadBalancer
  ports:
  - protocol:  TCP
    port:  80
    targetPort:  80
