apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: gcr.io/gcp-demo-200100/hello-world-nginx
  googleCloudBuild:
    projectId: gcp-demo-200100
deploy:
  kubectl:
    manifests:
    - https://raw.githubusercontent.com/tariq-islam/hello-world-nginx/master/hello-world-nginx-deploy.yaml
